# This is a basic workflow to help you get started with Actions

name: Action Practice

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Output a message
        run: echo "Action Complete!"
[![Action Practice](https://github.com/baneeen/codio/actions/workflows/actionPractice.yml/badge.svg)](https://github.com/baneeen/codio/actions/workflows/actionPractice.yml)
